namespace TradeGenius.WebApi.Application.Crypto.Coins;
public class CryptoCompareDto
{
    public string TYPE { get; set; }
    public string MARKET { get; set; }
    public string FROMSYMBOL { get; set; }
    public string TOSYMBOL { get; set; }
    public string FLAGS { get; set; }
    public double PRICE { get; set; }
    public double LASTUPDATE { get; set; }
    public double MEDIAN { get; set; }
    public double LASTVOLUME { get; set; }
    public double LASTVOLUMETO { get; set; }
    public string LASTTRADEID { get; set; }
    public double VOLUMEDAY { get; set; }
    public double VOLUMEDAYTO { get; set; }
    public double VOLUME24HOUR { get; set; }
    public double VOLUME24HOURTO { get; set; }
    public double OPENDAY { get; set; }
    public double HIGHDAY { get; set; }
    public double LOWDAY { get; set; }
    public double OPEN24HOUR { get; set; }
    public double HIGH24HOUR { get; set; }
    public double LOW24HOUR { get; set; }
    public string LASTMARKET { get; set; }
    public double VOLUMEHOUR { get; set; }
    public double VOLUMEHOURTO { get; set; }
    public double OPENHOUR { get; set; }
    public double HIGHHOUR { get; set; }
    public double LOWHOUR { get; set; }
    public double TOPTIERVOLUME24HOUR { get; set; }
    public double TOPTIERVOLUME24HOURTO { get; set; }
    public double CHANGE24HOUR { get; set; }
    public double CHANGEPCT24HOUR { get; set; }
    public double CHANGEDAY { get; set; }
    public double CHANGEPCTDAY { get; set; }
    public double CHANGEHOUR { get; set; }
    public double CHANGEPCTHOUR { get; set; }
    public string CONVERSIONTYPE { get; set; }
    public string CONVERSIONSYMBOL { get; set; }
    public double CONVERSIONLASTUPDATE { get; set; }
    public double SUPPLY { get; set; }
    public double MKTCAP { get; set; }
    public double MKTCAPPENALTY { get; set; }
    public double CIRCULATINGSUPPLY { get; set; }
    public double CIRCULATINGSUPPLYMKTCAP { get; set; }
    public double TOTALVOLUME24H { get; set; }
    public double TOTALVOLUME24HTO { get; set; }
    public double TOTALTOPTIERVOLUME24H { get; set; }
    public double TOTALTOPTIERVOLUME24HTO { get; set; }
    public string IMAGEURL { get; set; }
}
